#!/bin/bash

echo "Criando ambiente Python..."
python3 -m venv venv
echo "Criado com sucesso"

echo "Ativando ambiente Python..."
source venv/bin/activate
echo "Ativado com sucesso"

echo "Instalando bibliotecas..."
python -m pip install -r requirements.txt
echo "Configurado com sucesso!"
